app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),

    path('class/', views.class_list, name = 'class'),
    path('class/<int:pk>/', views.class_detail_view, name='detail'),
    
    path('write/', views.writeindex, name = 'writeindex'),
    path('write/<int:pk>/', views.newwrite, name = 'newwrite'),
    path('write/edit/<int:pk>/', views.edit, name = 'state_edit'),
    path('write/edit/', views.list, name = 'list'),

    path('faq/', views.faq, name = 'faq'),
    path('privacypolicy/', views.confidencial, name = 'confidencial'),
    path('delete/<int:pk>/', views.delete, name = 'delete'),

    path('login/', views.login, name = 'login'),
    path('logout/', views.logout_view, name = 'logout'),
    path('register/', views.register, name = 'register'),
    path('account/', views.account, name = 'account'),
    path('pasrec/', views.pasrec, name = 'pasrec'),

    path('update/', views.update, name = 'update')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User
import uuid

class SchoolClass(models.Model):
    school_class = models.CharField(max_length=10, help_text = 'Класс')
    stats = models.BigIntegerField(default=0)
    number = models.IntegerField()
    def __str__(self):
        return self.school_class
        # Возвращает id 0_о
    def get_absolute_url(self):
        return reverse('class-detail', args=[str(self.id)])
    class Meta:
    	ordering = ['number']

class People(models.Model):
    first_name = models.CharField(max_length=100, help_text = 'Имя учащегося')
    last_name = models.CharField(max_length=100, help_text = 'Фамилия учащегося')
    school_class = models.ForeignKey(SchoolClass, help_text = 'Класс ученика', on_delete = models.SET_NULL, null=True)
    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)
    def name(self):
        return '{} {}'.format(self.first_name, self.last_name)

class State(models.Model):
    date = models.DateField(help_text = '- в формате дд.мм.гггг')
    status = models.CharField(max_length=1)
    people = models.ManyToManyField(People, 
        help_text = '-выберите только тех, кто пришел!',
        related_name="peoples",
        blank = 'true')
    school_class = models.CharField(max_length=10)
    school_class_id = models.CharField(max_length=10)
    author = models.CharField(max_length=100)
    availability = models.CharField(max_length=2)

    def __str__(self):
        return '{} {}'.format(self.date, self.people.__str__())

    def get_absolute_url(self):
        return reverse('date-detail', args=[str(self.id)])

    class Meta:
        ordering = ['-date']

app/forms.py
from django import forms
from .models import State, People
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime

class DateInput(forms.DateInput):
    input_type='date'


class StateForm(forms.ModelForm):
    class Meta:
        model = State
        fields = ('date', 'people')
        labels = {
        	'people':_('Ученики'),
            'date':_('Дата')
        }
        widgets = {
            'date': DateInput(),
            }

class LoginForm(forms.Form):
    username = forms.CharField(
        label='Логин',
        max_length=100,
        error_messages={'required': 'Укажите логин'})
    password = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput,
        error_messages={'required': 'Укажите пароль'})
    widgets = {'password': forms.PasswordInput()}

class RegisterForm(forms.Form):
    username = forms.CharField(
        label='Логин',
        max_length=100,
        error_messages={'required': 'Укажите логин'})
    email = forms.EmailField(
        label='Электронная почта')
    first_name = forms.CharField(
        label='Имя',
        max_length=100,
        error_messages={'required': 'Укажите имя'})
    last_name = forms.CharField(
        label='Фамилия',
        max_length=100,
        error_messages={'required': 'Укажите фамилию'})
    password1 = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput,
        error_messages={'required': 'Укажите пароль'})
    password2 = forms.CharField(
        label='Повтор пароля',
        widget=forms.PasswordInput,
        error_messages={'required': 'Укажите повтор пароля'})
    widgets = {'password1': forms.PasswordInput(), 'password2': forms.PasswordInput()}

class PasrecForm(forms.Form):
    password = forms.CharField(
        label='Старый пароль',
        widget=forms.PasswordInput,
        error_messages={'required': 'Укажите старый пароль'})
    password1 = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput,
        error_messages={'required': 'Укажите новый пароль'})
    password2 = forms.CharField(
        label='Повтор пароля',
        widget=forms.PasswordInput,
        error_messages={'required': 'Укажите повтор нового пароля'})
    widgets = {'password1': forms.PasswordInput(), 'password2': forms.PasswordInput(), 'password': forms.PasswordInput()}

app/templates/app/account.html
{% extends "base_generic.html" %}

{% block title %}<title>Аккаунт</title>{% endblock %}

{% block content %}

<div class="container">
	{% if access == 'Writer' %}
		<div class="row">
			<div class="col-lg-6 pb-5">
				<h3 class="font-weight-normal">Меню аккаунта</<h3><p></p>

				<h5 class="font-weight-normal">Пользователь: {{ first_name }} {{ last_name }}</h5>

				<h5 class="font-weight-normal">Электронная почта: {{ email }}</h5>
				<h5 class="font-weight-normal">Права доступа: Редактор (доступ ко всем страницам сайта)</h5>
				<p></p>
				<a href="{% url 'logout' %}" class="btn btn-outline-primary">Выйти</a> <a href="{% url 'pasrec' %}" class="btn btn-outline-primary">Сменить пароль</a>
			</div>
			<div class="col-lg-6">
				<h3 class="font-weight-normal">Статистика</<h3><p></p>
				<h5 class="font-weight-normal">Всего записей: <a href="/write/edit/" class="a">{{state_list}}</a></h5>
				<h5 class="font-weight-normal">Ваши записи: {{state_your}}</h5>
				<h5><strong>Счастливого дня, <ins>{{ first_name }}</ins>!</strong></h5>
			</div>
		</div>
	{% else %}
		<h3 class="font-weight-normal">Меню аккаунта</<h3><p></p>

		<h5 class="font-weight-normal">Пользователь: {{ first_name }} {{ last_name }}</h5>

		<h5 class="font-weight-normal">Электронная почта: {{ email }}</h5>
		<h5 class="font-weight-normal">Права доступа: Простой пользователь (ограниченный доступ)</h5>
		<p></p>
		<a href="{% url 'logout' %}" class="btn btn-outline-primary">Выйти</a> <a href="{% url 'pasrec' %}" class="btn btn-outline-primary">Сменить пароль</a>
	{% endif %}
</div>

{% endblock %}

app/templates/app/delete.html
{% extends "base_generic.html" %}
{% block title %}<title>Удалить запись</title>{% endblock %}
{% block content %}
<div class="container">
	<h3 class="font-weight-normal">Удаление записи</<h3>

	<p></p>
	<h6 class="font-weight-normal">Вы действительно хотите удалить запись?</h6>
	<form method="POST" class="post-form">{% csrf_token %}
		<button type="submit" class="btn btn-outline-primary">Да, удалить</button>
		<a class="btn btn-outline-primary" href="{% url 'index' %}">Нет, верните меня на домашнюю страницу!</a>
	</form>
</div>




{% endblock %}

app/templates/app/edit.html
{% extends "base_generic.html" %}
{% block title %}<title>Изменить запись</title>{% endblock %}
{% load static %}
{% block static %}
<link rel="stylesheet" href="{% static 'css/multiple-select.css' %}">
<link rel="stylesheet" href="{% static 'css/datepicker.min.css' %}">
{% endblock %}
{% block content %}

<!-- value="{{statedate|date:'Y-d-m'}}" -->
<div class="container">
  <h3 class="font-weight-normal">Редактирование записи</<h3>

  <p></p>
  <form method="POST" class="post-form">{% csrf_token %}
      <h6 class="font-weight-normal">
      	<p>
	    		<label for="id_date">Дата:</label> 
	    		<input name="date" required="" id="id_date" type="text" autocomplete="off" readonly> 
	    		<span class="helptext">- в формате гггг-мм-дд</span>
	   	 	</p>
		   	<p>
		   	 	<label for="id_people">Ученики:</label>
					<select name="people" id="id_people" multiple="multiple">
						{% for i in people %}
		      		{{i}}
		      	{% endfor %}
					</select>
					<span class="helptext">-выберите только тех, кто пришел!</span>
				</p>
    	</h6>
      <button type="submit" class="save btn btn-outline-primary">Сохранить</button>
      <a href="{% url 'delete' id %}" class="btn btn-outline-primary">Удалить запись</a>
  </form>
</div>

<script src="{% static 'js/multiple-select.js' %}"></script>
<script src="{% static 'js/datepicker.min.js' %}"></script>
<script src="{% static 'js/datepickeredit.js' %}"></script>

<script>
	$('select').multipleSelect();


	var $picker = $('#id_date')

	$picker.datepicker({
		todayButton:new Date(),
		dateFormat: 'yyyy-mm-dd',
		altField:'yyyy-mm-dd',
		autoClose: true,
		clearButton: true,
		keyboardNav: false
	})

	var currentDate = new Date();
	$picker.data('datepicker').selectDate(new Date({{date.year}}, {{date.month}}-1, {{date.day}}))
</script>

{% endblock %}

app/templates/app/faq.html
{% extends "base_generic.html" %}
{% block title %}<title>Раздел Справочная</title>{% endblock %}
{% block content %}

<div class="container">
	<h3 class="font-weight-normal">Справочная</h3>
	<p></p>
	<h5 class="font-weight-normal">
		ЕшьУдобно - открытый проект учета посещения учениками заведения общепита. Разрабатывается и поддерживается одним человеком - tg: @KeltroHD, email: keltorplaylife@gmail.com. Ниже ответы на вопросы, которые могут возникнуть при взаимодействии с сайтом(из-за того, что я не дизайнер, а простой смертный с плохим чувством вкуса):
	</h5>

	<br>
	<div class="text-center font-weight-normal head">Возможности сервиса</div>
	<hr>
	<ul class="opon">
		<li class="li">Добавление записей о посещении учениками разных классов общепита (задание даты и количество людей)</li>
		<li class="li">Просмотр записей для разных классов (с фильтрами для удобного просмотра)</li>
		<li class="li">Скачивание Excel таблицы с данными посещения</li>
		<li class="li">Редактирование существующих записей (изменение даты и количество людей)</li>
		<li class="li">Система аккаунтов: Простые (Member) - только просмотр статистики, Редактор (Writer) - все права</li>
	</ul>
	<hr>

	<br>
	<div class="text-center font-weight-normal head">Вопрос - ответ по сервису</div>
	<hr>
	<div class="font-weight-normal ptr" onclick="ch_disp('A1')"><span>&#8659;</span> Как зарегистрировать аккаунт?</div>
	<div class="font-weight-normal answer" id="A1" style="display:none"><span>&#8658;</span> Перейти по <a href="/register/" target="_blank">ссылке</a>, ввести все данные, нажать конпку "зарегистрироваться"</div>

	<hr>

	<div class="font-weight-normal ptr" onclick="ch_disp('A2')">
		<span>&#8659;</span> 
		Как добавить данные о посещении заведения общепита?
	</div>
	<div class="font-weight-normal answer" id="A2" style="display:none">	
		<p><span>&#8658;</span>Все данные вносятся только <a href="/register/" target="_blank">зарегистрированными</a> пользователями!</p>
		Если есть аккаунт имеет все права (можно проверить на этой <a href="/account/" target="_blank">странице</a>): <br>
		Нужно перейти на страницу <a href="/write/" target="_blank">добавления новой записи</a>, выбрать класс (в левой колонке). Далее выбрать дату посещения и учеников, которые присутствовали. Нажимаете кнопку "сохранить" - запись добавлена! <p></p>
		Если аккаунт имеет права только на чтение: <br>
		Пишите на почту разработчика о наделении правами доступа, после их получения выполняете действия выше
	</div>
	
	<hr>

	<div class="font-weight-normal ptr" onclick="ch_disp('A3')">
		<span>&#8659;</span> 
		Как отредактировать или удалить добавленную запись?
	</div>
	<div class="font-weight-normal answer" id="A3" style="display:none">
		<span>&#8658;</span> Переходите на страницу <a href="/write/" target="_blank">добавления новой записи</a>, выбираете запись по дате и классу (в правой колонке). Далее нажимаете кнопку "удалить" или меняете дату, отмечаете учеников и нажимаете "сохранить"
	</div>

	<hr>

	<div class="font-weight-normal ptr" onclick="ch_disp('A4')">
		<span>&#8659;</span> 
		Как скачать статистику для класса?
	</div>
	<div class="font-weight-normal answer" id="A4" style="display:none">
		<p><span>&#8658;</span> Для скачивания статистики необходимо иметь статус редактор!</p>
		Перейдите на страницу <a href="/class/" target="_blank">просмотра статистики</a>, выберите класс. Внизу страницы будет кнопка "Скачать для Excel" - нажмите и загрузка начнется!
	</div>

	<hr>

	<div class="font-weight-normal ptr" onclick="ch_disp('A5')">
		<span>&#8659;</span> 
		Почему в статистике вместо имен учеников надпись "НгРФ"?
	</div>
	<div class="font-weight-normal answer" id="A5" style="display:none">
		<p><span>&#8658;</span> НгРФ - Неизвестный гражданин Российской федерации!</p>
		Имея простой аккаунт, можно просматривать статистику только на человека, имя и фамилию которого вы указали при регистрации! Статус редактора позволяет просматривать статистику на всех учеников!
	</div>

	<hr>

	<p class="lead">Не нашел нужного ответа? Напиши разработчику</p>

</div>

<script type="text/javascript" language="javascript">
var ch_disp = function( id )
{
	var el = document.getElementById( id );
	el.style.display = ( el.style.display == 'block' )? 'none' : 'block';
}
</script>

{% endblock %}

app/templates/app/list.html
{% extends "base_generic.html" %}
{% block title %}<title>Список последних записей</title>{% endblock %}
{% block content %}

<div class="container">
	<h3 class="font-weight-normal">Список последних 50 записей:</h3>
	<p></p>
	<ul class="ul">
	  {% for i in state %}
	    <h6 <h3 class="font-weight-normal"><li><a href="{{i.id}}">{{i.date}} - {{i.school_class}}</a></li>
	    </h6>
	  {% endfor %}
	</ul>
</div>



{% endblock %}

app/templates/app/login.html
<!DOCTYPE html>
<html lang="en">
<html>
    <head>

        <title>Авторизация</title>

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
        {% load static %}
        <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
        <link rel="stylesheet" href="{% static 'css/stylelogin.css' %}">
    </head>
    <body>

        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <h1 class="text-center"><a class="href" href="{% url 'index' %}">#ЕШЬУДОБНО</a> Авторизация</h1>
                    <p class="lead">Пожалуйста, введите ваш логин и пароль:</p>
                    <form id="contact-form" method='POST' class="form-signin post-form">{% csrf_token %}

                        <div class="controls">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="id_username">Логин</label>
                                        <input id="id_username" type="text" name="username" class="form-control" placeholder="Введите логин" required="required" data-error="Login is required." maxlength="100" >
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="id_password">Пароль</label>
                                        <input id="id_password" type="password" name="password" id="id_username" class="form-control" placeholder="Введите пароль" required="required" data-error="Firstname is required.">
                                    </div>
                                </div>
                            </div>

                            {% if error %}
                            <ul class="messages">
                                <li class="{{ error }}">{{ error }}</li>
                            </ul>
                            {% endif %}

                            <div class="row">

                                <div class="col-md-12">
                                    <button class="btn btn-lg btn-primary btn-block" type="submit">Войти</button>
                                </div>

                            </div>
                            <p>Нет аккаунта? <a href="{% url 'register' %}">Зарегистрироваться</a></p>
                            
                        </div>

                    </form>

                </div>

            </div> 

        </div>
    </body>
</html>

app/templates/app/newwrite.html
{% extends "base_generic.html" %}
{% block title %}<title>Новая запись</title>{% endblock %}
{% load static %}
{% block static %}
<link rel="stylesheet" href="{% static 'css/multiple-select.css' %}">
<link rel="stylesheet" href="{% static 'css/datepicker.min.css' %}">
{% endblock %}
{% block content %}


<div class="container">
	<h3 class="font-weight-normal">Новая запись</<h3>

	<p></p>
	<form method="POST" class="post-form">{% csrf_token %}
	    <h6 class="font-weight-normal">
	    	<p>
	    		<label for="id_date">Дата:</label> 
	    		<input name="date" required="" id="id_date" type="text" autocomplete="off" readonly> 
	    		<span class="helptext">- в формате гггг-мм-дд</span>
	   	 	</p>
		   	<p>
		   	 	<label for="id_people">Ученики:</label>
					<select name="people" id="id_people" multiple="multiple">
						{% for i in people %}
							<option value="{{i.id}}"> {{i}}</option>
						{% endfor %}
					</select>
					<span class="helptext">-выберите только тех, кто пришел!</span>
				</p>
			</h6>
	    <button type="submit" class="save btn btn-outline-primary">Сохранить</button>
	</form>
</div>

<script src="{% static 'js/multiple-select.js' %}"></script>
<script src="{% static 'js/datepicker.min.js' %}"></script>
<script src="{% static 'js/datepickerwrite.js' %}"></script>

{% endblock %}

app/templates/app/pasrec.html
<!DOCTYPE html>
<html lang="en">
<html>
    <head>

        <title>Смена пароля</title>

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
        {% load static %}
        <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
        <link rel="stylesheet" href="{% static 'css/stylelogin.css' %}">
    </head>
    <body>

        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <h1 class="text-center"><a class="href" href="{% url 'index' %}">#ЕШЬУДОБНО</a></h1> <h1 class="text-center">Смена пароля</h1>
                    <p class="lead">Пожалуйста, введите данные:</p>
                    <form id="contact-form" method='POST' class="form-signin post-form">{% csrf_token %}

                        <div class="controls">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="id_password">Старый пароль</label>
                                        <input id="id_password" type="password" name="password" class="form-control" placeholder="Введите старый пароль" required="required" maxlength="100" >
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="id_password">Новый пароль</label>
                                        <input id="id_password1" type="password" name="password1" id="id_username" class="form-control" placeholder="Введите новый пароль" required="required">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="id_password">Повтор нового пароля</label>
                                        <input id="id_password2" type="password" name="password2" id="id_username" class="form-control" placeholder="Новый пароль" required="required">
                                    </div>
                                </div>
                            </div>

                            {% if error %}
                            <ul class="messages">
                                <li class="{{ error }}">{{ error }}</li>
                            </ul>
                            {% endif %}

                            <div class="row">

                                <div class="col-md-12">
                                    <button class="btn btn-lg btn-primary btn-block" type="submit">Сменить пароль</button>
                                </div>

                            </div>
                            
                        </div>

                    </form>

                </div>

            </div> 

        </div>
    </body>
</html>

app/templates/app/permissions.html
{% extends "base_generic.html" %}
{% block title %}<title>Нет доступа!</title>{% endblock %}
{% block content %}

<div class="container">
	<h3 class="font-weight-normal">Нет доступа!</h3>
	<p></p>
	<h5 class="font-weight-normal">Для просмтора содержимого этой страницы необходимо иметь специальный доступ, для этого свяжитесь с разработчиком - keltorplaylife@gmail.com или напишите в tg - @KeltorHD</h5>
</div>


{% endblock %}

app/templates/app/register.html
<!DOCTYPE html>
<html lang="en">
<html>
    <head>

        <title>Регистрация</title>

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
        {% load static %}
        <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
        <link rel="stylesheet" href="{% static 'css/stylelogin.css' %}">
    </head>
    <body>

        <div class="container cls">
            <div class="row justify-content-center">
                <div class="col-lg-7">
                    <h1 class="text-center"><a class="href" href="{% url 'index' %}">#ЕШЬУДОБНО</a>. Регистрация</h1>
                    <p class="lead">Пожалуйста, введите данные для регистрации:</p>
                    <form id="contact-form" method='POST' class="form-signin post-form">{% csrf_token %}

                        <div class="controls">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="id_username">Имя</label>
                                        <input id="form_name" type="text" name="first_name" class="form-control" placeholder="Пожалуйста, введите ваше имя" required="required" data-error="Firstname is required." maxlength="100"  id="id_first_name">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="id_username">Фамилия</label>
                                        <input id="form_lastname" type="text" name="last_name" class="form-control" placeholder="Пожалуйста, введите вашу фамилию" required="required" data-error="Lastname is required." maxlength="100" id="id_last_name">
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="id_username">Логин</label>
                                        <input id="form_name" type="text" name="username" maxlength="100" id="id_username" class="form-control" placeholder="Логин - минимум 6 символов латиницей" required="required" data-error="Firstname is required.">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                     <div class="form-group">
                                        <label for="id_email">Электронная почта</label>
                                        <input id="form_name" type="email" name="email" class="form-control" placeholder="Введите вашу почту" required="required" data-error="Firstname is required." id="id_email">
                                    </div>
                                </div>
                            </div>
                            <div class="row end">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="id_password">Пароль</label>
                                        <input id="id_password1" type="password" name="password1" class="form-control" placeholder="Пароль - от 6 символов латиницей" required="required" data-error="Firstname is required.">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="id_password">Повторите пароль</label>
                                        <input id="id_password2" type="password" name="password2" class="form-control" placeholder="Пожалуйста, повторите пароль" required="required" data-error="Firstname is required.">
                                    </div>
                                </div>
                            </div>

                            {% if error %}
                            <ul class="messages">
                                <li class="{{ error }}">{{ error }}</li>
                            </ul>
                            {% endif %}

                            <div class="row">

                                <div class="col-md-12">
                                    <button class="btn btn-lg btn-primary btn-block" type="submit">Зарегистрироваться</button>
                                </div>

                            </div>
                            <p>Нажимая "Зарегистрироваться", вы соглашаетесь с <a href="{% url 'confidencial'%}">политикой конфиденциальности</a></p>
                            
                        </div>

                    </form>

                </div>

            </div> 

        </div>
    </body>
</html>

app/templates/app/schoolclass_list.html
{% extends "base_generic.html" %}
{% block title %}<title>Выберите класс</title>{% endblock %}
{% block content %}

<div class="container">
	<h3 class="font-weight-normal">Просмотр статистики</<h3>
	<p></p>
	<h5 class="font-weight-normal">Список всех классов, выберите один для просмотра статистики:</h5>
	<p></p>

	{% if view_class %}
		<div class="row">
			{% for i in view_class %}
				<div class="col-xs mb-4 mt-2">
					<ul class="ul">
						{% for d in i %}
							<li><a href='{{ d.id }}' class="href">{{d.school_class}} класс</a></li>
						{% endfor %}
					</ul>
				</div>
			{% endfor %}
		</div>
	{% else %}
		<li>Список пуст!</li>
	{% endif %}

</div>


{% endblock %}

app/templates/app/state_list.html
{% extends "base_generic.html" %}

{% block title %}<title>Статистика</title>{% endblock %}

{% block content %}

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/datatables.min.css' %}">

<script type="text/javascript" charset="utf8" src="{% static 'js/datatables.min.js' %}"></script>
<script type="text/javascript" charset="utf8" src="{% static 'js/dataTables.fixedColumns.min.js' %}"></script>

<div class="container">
  <h3 class="font-weight-normal">Просмотр статистики</h3>
  <p></p>
  {% if state %}
    <table id="table" class="table-responsive table-hover table display">
      <thead>
        <tr>
          <th><div class="font-weight-normal">День/Ученик</div></th>
          {% if access == 'Writer' %}
            {% for i in people %}
              <th><div class="font-weight-normal">{{i}}</div></th>
            {% endfor %}
          {% else %}
            {% for i in people %}
              <th><div class="font-weight-normal">{% if i.name == name %}{{i}}{% else %}<НгРФ>{% endif %}</div></th>
            {% endfor %}
          {% endif %}
        </tr>
      </thead>
      <tbody>
        {% for i in state %}
          <tr scope = "row">
            {% ifchanged i.date %}
              <td><div class="font-weight-normal">{{i.date|date:"d-m-y"}}</div></td>
              {% for d in people%}
                {% if d in i.people.all %}
                  <td><div class="font-weight-normal">+</div></td>
                {% else %}
                  <td><div class="font-weight-normal">-</div></td>
                {% endif %}
              {% endfor %}
            {% endifchanged %}
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <p></p>
    {% if request.user.groups.get.name == "Writer" %}
      <br>  
      <button type="button" class="btn btn-outline-primary" onclick="tableToExcel('table', 'Example')">Сохранить для Excel</button>
    {% endif %}
  {% else %}
    <h5 class="font-weight-normal">Нет ни одной записи</h5>
  {% endif %}
  <p></p>
  <p class="lead text-right stats">Просмотров: {{stats}}</p>
    

<script src="{% static 'js/table.js' %}"></script>
{% endblock %}